### PR TITLE
Added and revised Chinese Translation.

### PR DESCRIPTION
**Pull request by asqwedcxz741**

### CODE REVIEW

**Comment by asqwedcxz741** [comment]
In addition, I would like to discuss with you about the Chinese translation of PR 46. I checked the translation. There are many places where the translation of that friend is not clear and the quality is poor. He didn't proofread carefully

**Comment by asqwedcxz741** [comment]
As a matter of fact, I have finished all the Chinese translations for the [MFM] series, but I don't know how to merge them. Perhaps you need to create a Chinese [MFM]? Sorry, my English is not that good. These sentences are translated by machine.

**Comment by asqwedcxz741** [comment]
Of course, I know I don't have enough time to complete all the Chinese translations for PPJA. I still appreciate as8987000!

**Comment by as8987000** [comment]
Do you have QQ or WECHAT?

**Comment by paradigmnomad** [comment]
For MFM, if you want to leave a zip file of them that'd be great. Digus is working on adding translation support to MFM in the future. I have Korean translations as well that I'm holding onto until then.

I'll merge this PR but since @as8987000 had a question for @asqwedcxz741 I'll keep this open.

**Comment by asqwedcxz741** [comment]
> 您有QQ或微信吗？

YES，my wechat is QAQYYYQwQYYY  ，I really appreciate your contribution to ppja. I‘m looking forward to receiving your reply.

**Comment by asqwedcxz741** [comment]
> For MFM, if you want to leave a zip file of them that'd be great. Digus is working on adding translation support to MFM in the future. I have Korean translations as well that I'm holding onto until then.

Okay.I will upload the Chinese translation of [MFM] as soon as possible. Thank you again for your team's outstanding contribution to SDV.

**Pull request merged**
