### PR TITLE
Added 'Stardew Valley Expanded' gift preferences for 'Fruits and Vegg…

### PR DESCRIPTION
**Pull request by Shinx12345**
…ies' & 'Fresh Meat'.

Changed edibility ratings for several 'Fresh Meat' recipes to more in line with base game.
Changed 'Surimi' from 'More New Recipes' edibility to be more in line with base game 'sashimi'.
(Plans to work out a formula for balancing edibility/recipe use/profit for each item.)

### CODE REVIEW

**Comment by paradigmnomad** [comment]
Hi there :) Could you please resubmit your PR using the latest version that's on github? There's many entries in your PR that remove translations which would make sense if you were editing from the Nexus version. After that I'll happily review and merge the PR. Thanks!

**Comment by Shinx12345** [comment]
Oh, ok! I didn't even realise haha

**Comment by Shinx12345** [comment]
I might be a while. Sourcetree is confusing lol

**Comment by paradigmnomad** [comment]
Take your time! I'll keep an eye out for the updated PR.

**Comment by Shinx12345** [comment]
I think im out of my depth here. I cant even find sourcetree on my computer, plus, the files I edited are on my pc in a folder, so I imagine i'd have to re-do the work I already did if I used to wrong files as a base (which was hours of tedious work). Sorry everyone, but I have things i'd rather be doing to be honest. My respect for your hard work, though!

**Pull request closed without merging**
