### PR TITLE
Farmer to Florist complete Hungarian tr.

### PR DESCRIPTION
**Pull request by Macskasajt05**

### CODE REVIEW

**Comment by therealmate** [comment]
Update to 1.5 @Macskasajt05

**Comment by Macskasajt05** [comment]
Hi! I am so sorry, but how do I update my fork?

**Comment by therealmate** [comment]
Delete the fork, fork it again and make the changes again(That's how I'd do it.)

**Comment by Macskasajt05** [comment]
Oh well... Okay, thanks for the info.

**Comment by paradigmnomad** [comment]
This PR was actually fine except for some merge conflicts. Not sure if you removed the branch on your end since I couldn't actually open the PR to solve the merge conflicts, but I manually added the EMR translations and merged the other PR for the F2F trees.

Thank you as always :)

**Pull request closed without merging**
