### PR TITLE
Some tiny fixes

### PR DESCRIPTION
**Pull request by KediDili**
It fixes 2 or 3 mistranslations of mine. if there seem to be two commits, dont mind the first and huge one. (if there's such an option?) Ana I dunno why but special characters in translated letters seem to get missing in game. like 'sağlık' turns into 'sa l k'. I tried to do UTF-8 encoding by using notepad++(because translations wiki tells that), but doesnt seem to help or I couldn't do it right. Hope didn't mess up anything?

### CODE REVIEW

**Comment by paradigmnomad** [comment]
I'll manually add the other changes since the PR won't only do a specific commit (no worries!). Or it probably can but I don't know how.

I'm also not sure how to resolve the encoding issues. Looking at the font files, those characters are very much in the games files. I'll probably end up asking around. See if anybody else has run into the issue.

**Comment by KediDili** [comment]
Its ok then! I uploaded them to Google Drive : [Link](https://drive.google.com/drive/folders/1R0qUcC8meia1jypLJvN6eZgUFqWdUntT?usp=sharing) if you need it. ,

Separate quesiton : How to keep my repository ( KediDili/PPJA ) updated with yours ( paradigmnomad/PPJA )? 
                                And how to get rid of the first big commit??

**Comment by paradigmnomad** [comment]
Thanks! Can you also give an example of an in game item that is missing characters with the translation? I'm going to run some tests.

[Here's a guide to update a fork'd repo](https://adrientorris.github.io/github/how-to-update-a-forked-repository-from-the-ui-on-github).

As for removing a commit it's not as simple. [Here's a guide on StackOverflow](https://stackoverflow.com/questions/36168839/how-to-remove-commits-from-a-pull-request/36170904). I can't be much more help than that guide since I'm not super familiar with GitHub myself.

**Comment by KediDili** [comment]
Heya! Uh, so, I solved that missing character issue. It's nothing about XNBs. I thought I did UTF-8 but turns out I didn't. Probably I did it on something else and thought it was PPJA letters. Sorry for the bother!

**Pull request closed without merging**
